name: checkov-check

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions: read-all

jobs:
  checkov-check:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
            pip install -q -U urllib3 requests
            pip install -q checkov
      - name: checkout code
        uses: actions/checkout@v3
      - name: scan
        run: |
            checkov --directory $GITHUB_WORKSPACE --skip-check CKV2_GHA_1
